#!/bin/sh
# Checks how many packages need updating

red='#65350'
green='#99c794'
yellow='#ffc24b'
blue='#268bd2'
magenta='#cd00cd'
cyan='#73cef4'

#Need to update or it wont know theres new packages
pikaur -Sy > /dev/null 2>&1

pac=$(pacman -Qqu 2> /dev/null | wc -l)
aur=$(pikaur -Qqu 2> /dev/null | wc -l)
aur=$(awk -v a='$aur' -v p='$pac' 'BEGIN { printf a+b }')

[[ $pac == "0" ]] && [[ $aur == "0" ]] && colour=$blue|| colour=$red
echo "%{u$colour}$pac  $aur" || echo "%{u$colour}$pac  $aur"
