# Don't print a new line at the start of the prompt
add_newline = true
command_timeout = 1000

format = """
$time\
$username\
$hostname\
${custom.ssh}\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$nix_shell\
$python\
$cmd_duration\
$line_break\
$shell\
$jobs\
${custom.git-town-status}\
$character"""

[shell]
disabled = false

[time]
disabled = false
format = "[$time](yellow)"
time_format = "%H:%M"

[username]
disabled = false
show_always = true
style_root = "red bold"
style_user = "yellow bold"
format = " [$user]($style)"

[hostname]
disabled = false
ssh_only = false
ssh_symbol = ' via SSH 🌐'
style = "yellow bold"
format = "[$ssh_symbol](red bold)[ on ](grey)[$hostname]($style)"

[directory]
disabled = false
truncation_length = 8
truncate_to_repo = true
fish_style_pwd_dir_length = 1
style = "cyan bold"
read_only_style = "(red)READONLY"
format = "[ in ](grey)[$path]($style)[ $lock_symbol]($lock_style)"

[cmd_duration]
min_time = 2_000
format = "[ took](grey) [$duration](bold yellow)"
show_notifications = true

[python]
symbol = ""

[git_branch]
always_show_remote = true

[git_metrics]
disabled = false

[custom.git-town-status]
description = "Output `git town status --pending` into my prompt"
command = "git town status --pending"
when = ''' local git_status && git_status=$(git town status --pending) && [[ -n "$git_status" ]] '''
require_repo = true
symbol = "T"
style = "bg:yellow fg:black"
format = '[$symbol($output )]($style)'
