# Explicitly set prefix
set-option -g prefix C-b
bind-key C-b send-prefix

# Split panes using \ and =
bind '\' split-window -h
bind = split-window -v
unbind '"'
unbind %

# Easy config reload
bind r source-file ~/.config/tmux/tmux.conf
