# Explicitly set prefix
set-option -g prefix C-b
bind-key C-b send-prefix

# Split panes using \ and =
bind '\' split-window -h
bind = split-window -v
unbind '"'
unbind %

# Easy config reload
bind r source-file ~/.config/tmux/tmux.conf

# Resize with vim keys
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# Enable mouse
set -g mouse on
