# Don't print a new line at the start of the prompt
add_newline = true

format = """
$time\
$username\
$hostname\
${custom.ssh}\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$nix_shell\
$python\
$cmd_duration\
$line_break\
$jobs\
$character"""

[time]
disabled = false
format = "[$time](yellow)"
time_format = "%H:%M"

[username]
disabled = false
show_always = true
style_root = "red bold"
style_user = "yellow bold"
format = " [$user]($style)"

[hostname]
disabled = false
ssh_only = false
style = "yellow bold"
format = "[ on ](grey)[$hostname]($style)"

[custom.ssh]
when = 'test -n "$SSH_CLIENT"'
format = "(red)[ via ](grey)[$symbol $output]($style)"
symbol = "ﳣ"
command = "echo 'SSH'"
style = "red"

[directory]
disabled = false
truncation_length = 8
truncate_to_repo = true
fish_style_pwd_dir_length = 1
style = "cyan bold"
read_only_style = "(red)READONLY"
format = "[ in ](grey)[$path ]($style)[$lock_symbol]($lock_style)"

[cmd_duration]
min_time = 2_000
format = "[ took](grey) [$duration](bold yellow)"

[python]
symbol = ""
