# Enable ssh
enable-ssh-support

#config pinentry-program
pinentry-program /usr/bin/pinentry-curses

# Set caches
#default-cache-ttl-ssh 60480000
default-cache-ttl-ssh 6
max-cache-ttl-ssh 6
max-cache-ttl 6
default-cache-ttl 6

# Set default screen
display :0
