# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

# Dont restart with every alt press
toggle_key: RIGHT_CTRL
search_trigger: OFF

backend: Inject

# Number of ms between text injections
inject_delay: 1
key_delay: 1

disable_x11_fast_inject: false
x11_use_xclip_backend: true
paste_shortcut: SHIFT+INSERT
show_notifications: true
# clipboard_threshold: 10
apply_patch: false
