#!/bin/sh

###------------------###
###--- Autostarts ---###
###------------------###

# Set wallpaper
"$HOME/git/agendrum/agendrum.py" && feh --bg-center /tmp/wallpaper.png && /usr/bin/rm "$HOME/.fehbg" &
# Pull all my repos to keep them up to date
#"$HOME/git/scripts/shell/gitpullall" &

# Init lemonbars
"$XDG_CONFIG_HOME/lemonbar/init_top_bar.sh" &
"$XDG_CONFIG_HOME/lemonbar/init_bottom_bar.sh" &
"$HOME/git/scripts/shell/bspwm_desktopnamer.sh" &

# Reinit sxhkd to provide session specific bindings
"$HOME/git/scripts/shell/bspwm_output_desktops_to_sxhkd.sh" && killall sxhkd && sxhkd &

###-------------###
###--- BSPWM ---###
###-------------###
if [ "$(bspc query -M | wc -l)" -eq 2 ]; then
    bspc monitor DVI-D-2 -d 1 2 3 4 5 6
    bspc monitor HDMI-1 -d 7 8 9 0
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

# Make sure borders are always on
bspc config borderless_monocle   false
bspc config gapless_monocle      true

# Next window attaches to last created window
bspc config initial_polarity second_child

# Split window into 50/50
bspc config split_ratio 0.5

# Follow mouse
bspc config focus_follows_pointer true

# Dont flash yellow when opening new window
bspc config presel_feedback false

# Allow moving with mouse
bspc config pointer_modifier mod1
bspc config pointer_action1 move

###---------------###
###--- COLOURS ---###
###---------------###
bspc config border_width 1
bspc config window_gap 5
bspc config normal_border_color '#343d46'
bspc config active_border_color '#839496'
bspc config focused_border_color '#e65350'
