#!/bin/sh

###------------------###
###--- Autostarts ---###
###------------------###

HOST=$(paste /etc/hostname)

# Set wallpaper
if [ "$HOST" = "arch-X220" ]; then
  if [ "$(bspc query -M | wc -l)" -eq 2 ]; then
    "$HOME/git/agendrum/agendrum.py" --resolution 1366x768 && xwallpaper --output LVDS1 --center /tmp/wallpaper_1366x768.png &
    "$HOME/git/agendrum/agendrum.py" --resolution 1920x1080 && xwallpaper --output HDMI3 --center /tmp/wallpaper_1920x1080.png &
  else
    "$HOME/git/agendrum/agendrum.py" --resolution 1366x768 && xwallpaper --center /tmp/wallpaper_1366x768.png &
  fi
else
  "$HOME/git/agendrum/agendrum.py" && xwallpaper --center /tmp/wallpaper_1920x1080.png &
fi

# Init lemonbars
killall -9 lemonbar
"$XDG_CONFIG_HOME/lemonbar/init_top_bar.sh" &
"$XDG_CONFIG_HOME/lemonbar/init_bottom_bar.sh" &

# Reinit sxhkd to provide session specific bindings
"$HOME/git/scripts/shell/bspwm_output_desktops_to_sxhkd.sh" && killall sxhkd && sxhkd &
"$HOME/git/scripts/shell/bspwm_desktopnamer_subscriber.sh" &

# Start unclutter to remove cursor
pgrep unclutter || unclutter --timeout 3 --jitter 5 --ignore-buttons 1,2,3 --fork &

# Start redshift
killall -9 redshift && redshift -x && redshift -b 1.0:0.65 -l -31.9505:115.8605 -t 6500:6500 -m randr &

# Start syncthing
pgrep syncthing || syncthing --no-browser &

# Start espanso
#espanso daemon &

# Swallow windows
"$HOME/git/scripts/python/bspwm_swallow" &

# Disable right channel microphone
amixer sset 'Capture',0 frontright 0% &

###-------------###
###--- BSPWM ---###
###-------------###
if [ "$(bspc query -M | wc -l)" -eq 2 ]; then
    # Desktop screens
    # Basically sets HDMI as first monitor, even though its on the "right"
    #bspc wm --reorder-monitors HDMI3 LVDS1
    bspc monitor HDMI3 -d 7 8 9 0
    bspc monitor LVDS1 -d 1 2 3 4 5 6
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 0
fi

# Make sure borders are always on
bspc config borderless_monocle   false
bspc config gapless_monocle      true

# Next window attaches to last created window
bspc config initial_polarity second_child

# Split window into 50/50
bspc config split_ratio 0.5

# Follow mouse
bspc config focus_follows_pointer true

# Dont flash yellow when opening new window
bspc config presel_feedback false

# Allow moving with mouse
bspc config pointer_modifier mod1
bspc config pointer_action1 move

###---------------###
###--- COLOURS ---###
###---------------###
bspc config border_width 1
bspc config window_gap 5
bspc config normal_border_color '#343d46'
bspc config active_border_color '#839496'
bspc config focused_border_color '#e65350'

###-------------###
###--- RULES ---###
###-------------###
# Dont float zathura
bspc rule --add Zathura state=tiled
