#Set window title to format I like
title="${file-size} ${media-title} ${time-pos}/${duration} ${height}p - mpv"

## No terminal
#  no-terminal

[nosilence]
lavfi-complex='[aid1] silenceremove=1:0:-45dB:0:any:-1:0:-45dB:0:any:rms:0.002 [ao]'
hr-seek
