[sync]
alwaysshowpkgorigin = yes
develpkgsexpiration = -1
upgradesorting = versiondiff
showdownloadsize = yes
ignoreoutofdateaurupgrades = no

[build]
keepbuilddir = no
keepdevbuilddir = no
keepbuilddeps = no
gpgdir = /home/wynand/.config/gnupg/
skipfailedbuild = no
dynamicusers = never
ignorearch = no

[review]
noedit = no
donteditbydefault = no
nodiff = no
gitdiffargs = --ignore-space-change,--ignore-all-space
diffpager = auto
hidedifffiles = .SRCINFO

[colors]
version = 10
versiondiffold = 11
versiondiffnew = 9

[ui]
requireenterconfirm = yes
printcommands = no
aursearchsorting = hottest
displaylastupdated = yes
groupbyrepository = yes
reversesearchsorting = no
warnaboutpackageupdates = 
warnaboutnondefaultprivilegeescalationtool = yes

[misc]
cachepath = /home/wynand/.cache
datapath = /home/wynand/.local/share
pacmanpath = pacman
privilegeescalationtool = sudo
privilegeescalationtarget = pikaur
userid = 0
PreserveEnv = PKGDEST,VISUAL,EDITOR,http_proxy,https_proxy,ftp_proxy,HTTP_PROXY,HTTPS_PROXY,FTP_PROXY,ALL_PROXY,XDG_CACHE_HOME,XDG_CONFIG_HOME,XDG_DATA_HOME,XDG_STATE_HOME,CARGO_HOME,RUSTUP_HOME,GNUPGHOME,GOMODCACHE,GOPATH,GRADLE_USER_HOME,INPUTRC,LESSHISTFILE,MYPY_CACHE_DIR,NPM_CONFIG_USERCONFIG,PARALLEL_HOME,PYTHONPYCACHEPREFIX,PYTHONUSERBASE,PYTHON_HISTORY,RIPGREP_CONFIG_PATH,RUFF_CACHE_DIR,STARSHIP_CACHE,STARSHIP_CONFIG,TMUX_PLUGIN_MANAGER_PATH,WGETRC,_FASD_DATA,FFMPEG_DATADIR
groupid = 0

[network]
aururl = https://aur.archlinux.org
newsurl = https://archlinux.org/feeds/news/
socks5proxy = 
aurhttpproxy = 
aurhttpsproxy = 

