general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = hyprlock
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({action = "enable"})'
    ignore_wayland_inhibit = true
}

listener {
    timeout = 10
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({action = "disable"})' || pidof hyprlock || hyprlock
    on-resume = hyprctl dispatch 'hl.dsp.dpms({action = "enable"})'
}
