-- Dont autogenerate config when needed
hl.config({ autogenerated = false })

---------------------
---- MY PROGRAMS ----
---------------------
-- Set programs that you use
local terminal = "alacritty"
local fileManager = "dolphin"
local menu = "hyprlauncher"

-- Autostart
hl.on("hyprland.start", function()
	hl.exec_cmd("/home/wynand/git/hyprwyn/.venv/bin/python /home/wynand/git/hyprwyn/main.py &")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/
hl.env("XCURSOR_SIZE", "18")
hl.env("HYPRCURSOR_SIZE", "18")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

hl.config({
	misc = {
		mouse_move_enables_dpms = false,
		key_press_enables_dpms = true,
		animate_manual_resizes = true,
		focus_on_activate = true,
		allow_session_lock_restore = true,
	},
})

-----------------------
---- LOOK AND FEEL ----
-----------------------
require("theme")
require("keys")
