#############
### INPUT ###
#############
input {
    # Keyboard
    kb_layout = us,
    kb_options = caps:escape

    # Mouse
    follow_mouse = 1
    sensitivity = 0 # -1 to 1, 0 is no modification

    # Touchpad
    touchpad {
        natural_scroll = false
    }
}

###################
### KEYBINDINGS ###
###################
# Bind Flags
# bindl -> locked
# bindr -> trigger on release
# bindo -> long press
# binde -> will repeat if held
# bindn -> non-consuming. Will pass to active window along with triggering keybind
# bindm -> mouse
# bindt -> transparrent. Cannot be shaddowed
# bindi -> ignore mods
# binds -> will combine keys between each mod/key
# bindd -> has description as a variable (Mod, keys, description, dispatcher, params)
# bindp -> bypasses requests by apps to inhibit

# Set variables
$mod = Alt
$terminal = alacritty

# Programs
bind = $mod, Return, exec, $terminal
bind = $mod, f, exec, firefox
bind = $mod, s, exec, signal-desktop
bind = $mod, x, exec, hyprlock

# Window Management
bind = $mod, q, killactive

# Navigation
## Focus
bind = $mod, l, movefocus, r
bind = $mod, h, movefocus, l
bind = $mod, j, movefocus, d
bind = $mod, k, movefocus, u

## Workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

## Move to workspaces
bind = $mod+SHIFT, 1, movetoworkspace, 1
bind = $mod+SHIFT, 2, movetoworkspace, 2
bind = $mod+SHIFT, 3, movetoworkspace, 3
bind = $mod+SHIFT, 4, movetoworkspace, 4
bind = $mod+SHIFT, 5, movetoworkspace, 5
bind = $mod+SHIFT, 6, movetoworkspace, 6
bind = $mod+SHIFT, 7, movetoworkspace, 7
bind = $mod+SHIFT, 8, movetoworkspace, 8
bind = $mod+SHIFT, 9, movetoworkspace, 9
bind = $mod+SHIFT, 0, movetoworkspace, 10

## Toggles fullscreen
bind = $mod, Space, fullscreen, 1

bind = $mod, Tab, workspace, previous

#XF86 keys
#bindl = XF86AudioMute
bindl = $mod, F5, exec, brightnessctl set 5%-
bindl = $mod, F6, exec, brightnessctl set 5%+

bindl = $mod, F1, exec, pactl set-sink-volume @DEFAULT_SINK@ 0%
bindl = $mod, F2, exec, pactl set-sink-volume @DEFAULT_SINK@ -5%
bindl = $mod, F3, exec, pactl set-sink-volume @DEFAULT_SINK@ +5%
