"""--------------------------"""
"""--- Precursor Settings ---"""
"""--------------------------"""
"Set the window’s title, reflecting the file currently being edited.
set title

" Use Vim settings, dont even pretend to be Vi
" This must be first, because it changes other options as a side effect.
set nocompatible

"""--------------------"""
"""--- XDG Settings ---"""
"""--------------------"""
set undodir=$XDG_DATA_HOME/vim/undo
set directory=$XDG_DATA_HOME/vim/swap
set backupdir=$XDG_DATA_HOME/vim/backup
set viewdir=$XDG_DATA_HOME/vim/view
set viminfo+='1000,n$XDG_DATA_HOME/vim/viminfo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after

"""------------------------"""
"""--- General Settings ---"""
"""------------------------"""
" Vertically center document when entering insert mode
augroup niceties
    autocmd InsertEnter * norm zz
augroup END

"New lines inherit the indentation of previous lines
set autoindent

"Proper line join removes comment flags
set formatoptions+=j
"Dont insert comment leader in new line
set formatoptions-=ro

"Use system clipboard as well as buffers
set clipboard+=unnamedplus

"Line numbers are good
set number

"Sets cursorline
set cursorline

"Allow backspace in insert mode
set backspace=indent,eol,start

"Store lots of :cmdline history
set history=1000

"Show incomplete cmds down the bottom
set showcmd

"Show current mode down the bottom
set showmode

"Disable cursor blink
set guicursor=a:blinkon0

"Reload files changed outside vim
set autoread

"Set the time in milliseconds you have to complete a key-press combo
set timeoutlen=1000
set ttimeoutlen=10

"Highlight matching brackets etc
set showmatch

" Hide the mouse cursor while typing
set mousehide

"Everything is in UTF
scriptencoding utf-8
" '.' is an end of word designator
set iskeyword-=.
" '"' is an end of word designator
set iskeyword-="
" '-' is an end of word designator
set iskeyword-=-
" '_' is an end of word designator
set iskeyword-=_

" Maximum number of changes that can be undone
set undolevels=1000

" Maximum number lines to save for undo on a buffer reload
set undoreload=10000

" Case insensitive search
set ignorecase

" Case sensitive when uc present
set smartcase

" Uses spellcheck in vim
"set spell spelllang=en_au

" Puts new vsplit windows to the right of the current
set splitright

" Puts new split windows to the bottom of the current
set splitbelow

" Buffers exist in the background
set hidden

"Insert “tabstop” number of spaces when the “tab” key is pressed.
set smarttab
set softtabstop=4
set tabstop=4
set expandtab
"When shifting lines, round the indentation to the nearest multiple of “shiftwidth.”
set shiftwidth=4
set shiftround

" Display tabs and trailing spaces visually
set list listchars=tab:\ \ ,trail:·

"Do wrap lines
set wrap

"Avoid wrapping a line in the middle of a word.
set linebreak

"Allow me to fold by my settings
set foldmethod=indent

"Only fold up to three nested levels.
set nofoldenable
set foldnestmax=3

"Don’t update screen during macro and script execution.
"set lazyredraw

"Display command line’s tab complete options as a menu.
set wildmenu

"Enable syntax highlighting
syntax enable
au BufNewFile,BufRead * if &syntax == '' | set syntax=dosini | endif

"""----------------"""
"""--- keyboard ---"""
"""----------------"""
let mapleader = ','

"Stolen from CIA Hack, save file you forgot to open as root
cmap w!! %!sudo tee > /dev/null %

"Navigating with guides
inoremap <Space><Space> <Esc>/<++><Enter>"_c4l

"Pressing :sc will toggle and untoggle spell checking
map <leader>sc :setlocal spell!<cr>

"Spell add word to dictionary
" ]s is go to next spelling error
" zg adds to dictionary
map <leader>sa <Esc>]szg

" leader cs corrects spelling by choosing the first suggestion
" 1z= is choose first suggestion
" ]s is go to next spelling error
map <leader>cs <Esc>]s1z=

"Insert the line number
map <leader>ln :execute "normal! i" . ( line("."))<cr>

" Split vim using leader keys
nnoremap <Leader>l :vsp<CR>
nnoremap <Leader>j :sp<CR>

"split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Save file using leader w
nnoremap <Leader>w :w<CR>

"Remaps backspace to move back a paragraph
nnoremap <BS> {
onoremap <BS> {
vnoremap <BS> {

"Remaps enter to move forward a paragraph
nnoremap <expr> <CR> empty(&buftype) ? '}' : '<CR>'
onoremap <expr> <CR> empty(&buftype) ? '}' : '<CR>'
vnoremap <CR> }

"using the PRIMARY clipboard * with the y and p commands
noremap <Leader>y "*y
noremap <Leader>p "*p
noremap <Leader>Y "+y
noremap <Leader>P "+p


"""-------------------------"""
"""--- Template Settings ---"""
"""-------------------------"""
"LATEX
if has('autocmd')
  augroup latex
    autocmd FileType tex inoremap ;em \emph{}<++><Esc>T{i
    autocmd FileType tex inoremap ;bf \textbf{}<++><Esc>T{i
    autocmd FileType tex inoremap ;it \textit{}<++><Esc>T{i
    autocmd FileType tex inoremap ;tc \textcite{}<++><Esc>T{i
    autocmd FileType tex inoremap ;pc \parencite{}<++><Esc>T{i
    autocmd FileType tex inoremap ;ol \begin{enumerate}<Enter><Tab>\end{enumerate}<Enter><Tab><++><Esc>2kA<Enter><Tab>\item<Space>
    autocmd FileType tex inoremap ;ul \begin{itemize}<Enter><Tab>\end{itemize}<Enter><Tab><++><Esc>2kA<Enter><Tab>\item<Space>
    autocmd FileType tex inoremap ;li \item<Space>
    autocmd FileType tex inoremap ;chap \chapter{}<Enter><Tab><++><Esc>-f}i
    autocmd FileType tex inoremap ;sec \section{}<Enter><Tab><++><Esc>-f}i
    autocmd FileType tex inoremap ;ssec \subsection{}<Enter><Tab><++><Esc>-f}i
    autocmd FileType tex inoremap ;sssec \subsubsection{}<Enter><Tab><++><Esc>-f}i
    autocmd FileType tex inoremap ;ques \begin{questions}<Enter><Tab>\end{questions}<Enter><Tab><++><Esc>2kA<Enter><Tab>\newquestion{}<Space>
    autocmd FileType tex inoremap ;part \begin{parts}<Enter><Tab>\end{parts}<Enter><Tab><++><Esc>2kA<Enter><Tab>\newpart{}<Space>
  augroup END
endif

"if has('autocmd')
  "augroup templates
    "autocmd BufNewFile *.tex 0r ~/.vim/templates/skeleton_docs.tex
    "autocmd BufNewFile *.service 0r ~/.vim/templates/skeleton.service
    "autocmd BufNewFile *.timer 0r ~/.vim/templates/skeleton.timer
    "autocmd BufNewFile *.py 0r ~/.vim/templates/skeleton.py
    "autocmd BufNewFile *.sh 0r ~/.vim/templates/skeleton.sh
    "autocmd BufNewFile *soln.md 0r ~/.vim/templates/skeleton_soln.md
    "autocmd BufNewFile *beamer*.md 0r ~/.vim/templates/skeleton_beamer.md
    "autocmd BufNewFile README.md 0r ~/.vim/templates/skeleton_readme.md
    "autocmd BufNewFile CONTRIBUTING.md 0r ~/.vim/templates/skeleton_contributing.md
  "augroup END
"endif

augroup markdown
  autocmd FileType markdown let g:indentLine_enabled=0
augroup END


"""---------------"""
"""--- Plugins ---"""
"""---------------"""
call plug#begin('~/.config/vim/plugged')
"Linter
"Install shellcheck, vint, python-pylint from aur
Plug 'https://github.com/w0rp/ale.git' "linter

"improved incrimental searching
Plug 'https://github.com/haya14busa/incsearch.vim.git'

"tables in vim
Plug 'https://github.com/dhruvasagar/vim-table-mode.git'

"better indenting
Plug 'https://github.com/Yggdroot/indentLine.git'

"plugins for automated bullet lists
Plug 'https://github.com/dkarter/bullets.vim'

"expand region
Plug 'https://github.com/terryma/vim-expand-region.git'

"language pack
Plug 'https://github.com/sheerun/vim-polyglot.git'
Plug 'https://github.com/chrisbra/csv.vim' "polyglot-csv
Plug 'https://github.com/LaTeX-Box-Team/LaTeX-Box' "polyglot-latex
Plug 'https://github.com/vim-python/python-syntax' "polyglot-python
Plug 'https://github.com/rust-lang/rust.vim' "polyglot-rust
Plug 'https://github.com/elzr/vim-json' "polyglot-json
Plug 'https://github.com/plasticboy/vim-markdown' "polyglot-markdown
Plug 'https://github.com/baskerville/vim-sxhkdrc' "polyglot-sxhkd
Plug 'https://github.com/wgwoods/vim-systemd-syntax' "polyglot-systemd

"latex and vim
Plug 'https://github.com/lervag/vimtex.git'

"Ultisnips
"Ultisnips is the completion engine that reads vim-snippets
Plug 'https://github.com/sirver/ultisnips'
Plug 'https://github.com/honza/vim-snippets'

"Youcompleteme
""Need YouCompleteMe for a nice popup interface for ultisnips
"Install vim-youcompleteme-git from aur

"Supertab
""Need SuperTab to allow YouCompleteMe selection to expand
Plug 'https://github.com/ervandew/supertab'
call plug#end()

"""---"""
"""Ale"""
"""---"""
let g:ale_sign_column_always = 1
let g:ale_echo_msg_error_str = 'E'
let g:ale_echo_msg_warning_str = 'W'
let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
let g:ale_lint_on_save = 1
let g:ale_linters_explicit = 1
let g:ale_list_vertical = 1

let g:ale_linters = {'latex': ['redpen', 'chktex'], 'python': ['pylint'], 'vim': ['vint'], 'zsh': ['shellcheck']}
let g:ale_fixers = {'latex': ['redpen', 'chktex'], 'python': ['yapf'], 'zsh': ['shellcheck']}

"""----------"""
"""Inc-search"""
"""----------"""
map / <Plug>(incsearch-forward)
map ? <Plug>(incsearch-backward)
map g/ <Plug>(incsearch-stay)

"""------"""
"""Expand"""
"""------"""
"Hit v to visually select character, again to select word, again to select paragraph
vmap v <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)

"""---------"""
"""UltiSnips"""
"""---------"""
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>', 'J']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>', 'K']
let g:SuperTabDefaultCompletionType = '<C-n>'

" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = '<tab>'
let g:UltiSnipsJumpForwardTrigger = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'
