return {

	"MeanderingProgrammer/render-markdown.nvim",

	dependencies = {
		"nvim-treesitter/nvim-treesitter",
		"nvim-mini/mini.icons",
		"folke/which-key.nvim",
	},
	ft = { "markdown", "tex" },
	opts = {
		completions = {
			lsp = {
				enabled = true,
			},
		},
		bullet = {
			enabled = true,
			render_modes = false,
			icons = { "●", "○", "◆", "◇" },
			ordered_icons = function(ctx)
				local value = vim.trim(ctx.value)
				local index = tonumber(value:sub(1, #value - 1))
				return ("%d."):format(index > 1 and index or ctx.index)
			end,
			left_pad = 0,
			right_pad = 0,
			highlight = "RenderMarkdownBullet",
			scope_highlight = {},
			scope_priority = nil,
		},
		callout = {
			note = {
				raw = "[!NOTE]",
				rendered = "󰋽 Note",
				highlight = "RenderMarkdownInfo",
				category = "github",
			},
			tip = {
				raw = "[!TIP]",
				rendered = "󰌶 Tip",
				highlight = "RenderMarkdownSuccess",
				category = "github",
			},
			important = {
				raw = "[!IMPORTANT]",
				rendered = "󰅾 Important",
				highlight = "RenderMarkdownHint",
				category = "github",
			},
			warning = {
				raw = "[!WARNING]",
				rendered = "󰀪 Warning",
				highlight = "RenderMarkdownWarn",
				category = "github",
			},
			caution = {
				raw = "[!CAUTION]",
				rendered = "󰳦 Caution",
				highlight = "RenderMarkdownError",
				category = "github",
			},
			abstract = {
				raw = "[!ABSTRACT]",
				rendered = "󰨸 Abstract",
				highlight = "RenderMarkdownInfo",
				category = "obsidian",
			},
			summary = {
				raw = "[!SUMMARY]",
				rendered = "󰨸 Summary",
				highlight = "RenderMarkdownInfo",
				category = "obsidian",
			},
			tldr = {
				raw = "[!TLDR]",
				rendered = "󰨸 Tldr",
				highlight = "RenderMarkdownInfo",
				category = "obsidian",
			},
			info = {
				raw = "[!INFO]",
				rendered = "󰋽 Info",
				highlight = "RenderMarkdownInfo",
				category = "obsidian",
			},
			todo = {
				raw = "[!TODO]",
				rendered = "󰗡 Todo",
				highlight = "RenderMarkdownInfo",
				category = "obsidian",
			},
			hint = {
				raw = "[!HINT]",
				rendered = "󰌶 Hint",
				highlight = "RenderMarkdownSuccess",
				category = "obsidian",
			},
			success = {
				raw = "[!SUCCESS]",
				rendered = "󰄬 Success",
				highlight = "RenderMarkdownSuccess",
				category = "obsidian",
			},
			check = {
				raw = "[!CHECK]",
				rendered = "󰄬 Check",
				highlight = "RenderMarkdownSuccess",
				category = "obsidian",
			},
			done = {
				raw = "[!DONE]",
				rendered = "󰄬 Done",
				highlight = "RenderMarkdownSuccess",
				category = "obsidian",
			},
			question = {
				raw = "[!QUESTION]",
				rendered = "󰘥 Question",
				highlight = "RenderMarkdownWarn",
				category = "obsidian",
			},
			help = {
				raw = "[!HELP]",
				rendered = "󰘥 Help",
				highlight = "RenderMarkdownWarn",
				category = "obsidian",
			},
			faq = {
				raw = "[!FAQ]",
				rendered = "󰘥 Faq",
				highlight = "RenderMarkdownWarn",
				category = "obsidian",
			},
			attention = {
				raw = "[!ATTENTION]",
				rendered = "󰀪 Attention",
				highlight = "RenderMarkdownWarn",
				category = "obsidian",
			},
			failure = {
				raw = "[!FAILURE]",
				rendered = "󰅖 Failure",
				highlight = "RenderMarkdownError",
				category = "obsidian",
			},
			fail = {
				raw = "[!FAIL]",
				rendered = "󰅖 Fail",
				highlight = "RenderMarkdownError",
				category = "obsidian",
			},
			missing = {
				raw = "[!MISSING]",
				rendered = "󰅖 Missing",
				highlight = "RenderMarkdownError",
				category = "obsidian",
			},
			danger = {
				raw = "[!DANGER]",
				rendered = "󱐌 Danger",
				highlight = "RenderMarkdownError",
				category = "obsidian",
			},
			error = {
				raw = "[!ERROR]",
				rendered = "󱐌 Error",
				highlight = "RenderMarkdownError",
				category = "obsidian",
			},
			bug = {
				raw = "[!BUG]",
				rendered = "󰨰 Bug",
				highlight = "RenderMarkdownError",
				category = "obsidian",
			},
			example = {
				raw = "[!EXAMPLE]",
				rendered = "󰉹 Example",
				highlight = "RenderMarkdownHint",
				category = "obsidian",
			},
			quote = {
				raw = "[!QUOTE]",
				rendered = "󱆨 Quote",
				highlight = "RenderMarkdownQuote",
				category = "obsidian",
			},
			cite = {
				raw = "[!CITE]",
				rendered = "󱆨 Cite",
				highlight = "RenderMarkdownQuote",
				category = "obsidian",
			},
		},
		checkbox = {
			enabled = true,
			render_modes = false,
			bullet = false,
			left_pad = 0,
			right_pad = 1,
			unchecked = {
				icon = "󰄱 ",
				highlight = "RenderMarkdownUnchecked",
				scope_highlight = nil,
			},
			checked = {
				icon = "󰱒 ",
				highlight = "RenderMarkdownChecked",
				scope_highlight = "@markup.strikethrough",
			},
			custom = {
				todo = {
					raw = "[-]",
					rendered = "󰥔 ",
					highlight = "RenderMarkdownTodo",
					scope_highlight = nil,
				},
			},
			scope_priority = nil,
		},
		code = {
			enabled = true,
			render_modes = false,
			sign = true,
			conceal_delimiters = true,
			language = true,
			position = "left",
			language_icon = true,
			language_name = true,
			language_info = true,
			language_pad = 0,
			disable = {},
			disable_background = { "diff" },
			background_inset = 1,
			width = "full",
			left_margin = 0,
			left_pad = 4,
			right_pad = 0,
			min_width = 0,
			border = "hide",
			language_border = "█",
			language_left = "",
			language_right = "",
			above = "▄",
			below = "▀",
			inline = true,
			inline_left = "",
			inline_right = "",
			inline_pad = 0,
			priority = 140,
			highlight = "RenderMarkdownCode",
			highlight_info = "RenderMarkdownCodeInfo",
			highlight_language = nil,
			highlight_border = "RenderMarkdownCodeBorder",
			highlight_fallback = "RenderMarkdownCodeFallback",
			highlight_inline = "RenderMarkdownCodeInline",
			highlight_inline_left = nil,
			highlight_inline_right = nil,
			style = "full",
		},
		dash = {
			enabled = true,
			render_modes = false,
			icon = "─",
			width = "full",
			left_margin = 0,
			priority = nil,
			highlight = "RenderMarkdownDash",
		},
		heading = {
			enabled = true,
			render_modes = false,
			atx = true,
			setext = true,
			sign = true,
			icons = {
				"󰫎 ",
				"󰫎󰫎 ",
				"󰫎󰫎󰫎 ",
				"󰫎󰫎󰫎󰫎 ",
				"󰫎󰫎󰫎󰫎󰫎 ",
				"󰫎󰫎󰫎󰫎󰫎󰫎 ",
			},
			position = "overlay",
			signs = { "󰫎 " },
			width = "full",
			left_margin = 0,
			left_pad = 0,
			right_pad = 0,
			min_width = 0,
			border = false,
			border_virtual = false,
			border_prefix = false,
			above = "▄",
			below = "▀",
			backgrounds = {
				"RenderMarkdownH1Bg",
				"RenderMarkdownH2Bg",
				"RenderMarkdownH3Bg",
				"RenderMarkdownH4Bg",
				"RenderMarkdownH5Bg",
				"RenderMarkdownH6Bg",
			},
			foregrounds = {
				"RenderMarkdownH1",
				"RenderMarkdownH2",
				"RenderMarkdownH3",
				"RenderMarkdownH4",
				"RenderMarkdownH5",
				"RenderMarkdownH6",
			},
			custom = {},
		},
		indent = {
			enabled = false,
			render_modes = false,
			per_level = 4,
			skip_level = 1,
			skip_heading = false,
			icon = "|",
			priority = 0,
			highlight = "RenderMarkdownIndent",
		},
		latex = {
			enabled = true,
			render_modes = false,
			converter = { "utftex", "latex2text" },
			inline = true,
			block = true,
			highlight = "RenderMarkdownMath",
			position = "center",
			top_pad = 0,
			bottom_pad = 0,
		},
		link = {
			enabled = true,
			render_modes = false,
			footnote = {
				enabled = true,
				icon = "󰯔 ",
				body = function(ctx)
					return ctx.text
				end,
				superscript = true,
				prefix = "",
				suffix = "",
			},
			image = "󰥶 ",
			image_custom = true,
			email = "󰀓 ",
			hyperlink = "󰌹 ",
			highlight = "RenderMarkdownLink",
			highlight_title = "RenderMarkdownLinkTitle",
			wiki = {
				enabled = true,
				icon = "󱗖 ",
				conceal_destination = true,
				body = function()
					return nil
				end,
				highlight = "RenderMarkdownWikiLink",
				scope_highlight = nil,
			},
			custom = {
				web = { icon = "󰖟 ", pattern = "^http" },
				discord = { icon = "󰙯 ", pattern = "discord%.com", kind = "url" },
				github = { icon = "󰊤 ", pattern = "github%.com", kind = "url" },
				gitlab = { icon = "󰮠 ", pattern = "gitlab%.com", kind = "url" },
				google = { icon = "󰊭 ", pattern = "google%.com", kind = "url" },
				hackernews = { icon = " ", pattern = "ycombinator%.com", kind = "url" },
				linkedin = { icon = "󰌻 ", pattern = "linkedin%.com", kind = "url" },
				microsoft = { icon = " ", pattern = "microsoft%.com", kind = "url" },
				neovim = { icon = " ", pattern = "neovim%.io", kind = "url" },
				reddit = { icon = "󰑍 ", pattern = "reddit%.com", kind = "url" },
				slack = { icon = "󰒱 ", pattern = "slack%.com", kind = "url" },
				stackoverflow = { icon = "󰓌 ", pattern = "stackoverflow%.com", kind = "url" },
				steam = { icon = " ", pattern = "steampowered%.com", kind = "url" },
				twitter = { icon = " ", pattern = "twitter%.com", kind = "url" },
				wikipedia = { icon = "󰖬 ", pattern = "wikipedia%.org", kind = "url" },
				x = { icon = " ", pattern = "x%.com", kind = "url" },
				youtube = { icon = "󰗃 ", pattern = "youtube[^.]*%.com", kind = "url" },
				youtube_short = { icon = "󰗃 ", pattern = "youtu%.be", kind = "url" },
			},
		},
		pipe_table = {
			enabled = true,
			render_modes = false,
			preset = "round",
			cell = "padded",
			cell_offset = function()
				return 0
			end,
			padding = 1,
			min_width = 0,
			border_enabled = true,
			border_virtual = false,
			alignment_indicator = "━",
			head = "RenderMarkdownTableHead",
			row = "RenderMarkdownTableRow",
			style = "full",
		},
		quote = {
			enabled = true,
			render_modes = false,
			icon = "▋>",
			repeat_linebreak = false,
			highlight = {
				"RenderMarkdownQuote1",
				"RenderMarkdownQuote2",
				"RenderMarkdownQuote3",
				"RenderMarkdownQuote4",
				"RenderMarkdownQuote5",
				"RenderMarkdownQuote6",
			},
		},
	},

	keys = {},

	config = function(_, opts)
		require("render-markdown").setup(opts)
	end,
}
